### ISSUE TITLE
Clicking on select elements doesn't work

### ISSUE THREAD

**Issue by ashbythorpe** [rstudio/chromote#131]
When you click on a select element using chromote, the dropdown list does not appear.

``` r
library(chromote)

session <- ChromoteSession$new()

session$view()

html <- "
<select name='select'>
  <option value='1'>One</option>
  <option value='2'>Two</option>
</select>
"

session$Page$navigate(
  paste0("data:text/html,", URLencode(html))
)

document <- session$DOM$getDocument()
select_id <- session$DOM$querySelector(document$root$nodeId, "select")$nodeId

coords <- session$DOM$getBoxModel(select_id)$model$content
x <- (coords[[1]] + coords[[3]]) / 2
y <- (coords[[2]] + coords[[6]]) / 2

rlang::try_fetch(
  session$Input$dispatchMouseEvent(
    type = "mousePressed",
    x = x,
    y = y,
    button = "left",
    clickCount = 1,
    timeout_ = 0.1
  ),
  error = function(e) {
    if (grepl("timed out waiting for response", e$message, fixed = TRUE)) {
      NULL
    } else {
      rlang::zap()
    }
  }
)

rlang::try_fetch(
  session$Input$dispatchMouseEvent(
    type = "mouseReleased",
    x = x,
    y = y,
    button = "left",
    clickCount = 0,
    timeout_ = 0.1
  ),
  error = function(e) {
    if (grepl("timed out waiting for response", e$message, fixed = TRUE)) {
      NULL
    } else {
      rlang::zap()
    }
  }
)
```

The above code creates a basic page with a select input, and then clicks on it. The element is clicked, but the dropdown list doesn't appear:

Before (images are pixellated because the element is small):
![image](https://github.com/rstudio/chromote/assets/61390103/08028262-21b4-491b-bea3-a1234f072660)

After:
![image](https://github.com/rstudio/chromote/assets/61390103/aeb397c8-2af4-422a-8cf1-656b00de70a4)

Is this a known issue with CDP?

**Comment by gadenbuie** [comment]
There's a good chance it's normal CDP behavior. 

Note that there's a small bug in your reprex code (in case that's similar to code you're using). The return value of `$DOM$getBoxModel()$model$content` is a [Quad object](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#type-Quad), which is a series of four unlabelled `(x, y)` points, as `list(x1, y1, x2, y2, ..., x4, y5)`. To click on the center of the element, you could use this code instead:

```r
coords <- session$DOM$getBoxModel(select_id)$model$content
x <- unlist(coords[seq(1, 7, 2)]) |> range() |> mean()
y <- unlist(coords[seq(2, 8, 2)]) |> range() |> mean()
```

When running that locally, I can tell that the click has landed on the element because it gains focus, but no dropdown is revealed. Going out on a limb, my guess is that this is related to CDP's use of mobile mode and that somehow the select menu is handled differently with mobile emulation enabled. (That's something you could look into.)

**Comment by ashbythorpe** [comment]
Yes, I think you're right: on mobile, select menus are handled differently:

![image](https://github.com/rstudio/chromote/assets/61390103/af1d26a1-d267-4eb7-a673-4075cb4b9e8b)

I tried playing around with [CDP's emulation options](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/) but didn't have any success in changing the behaviour of the select input.
