### ISSUE TITLE
How to increase timeout to fix: Chromote: timed out waiting for response to command Page.disable

### ISSUE THREAD

**Issue by Montereytony** [rstudio/chromote#133]
When running this line in an IRkernel 4.2.2:

fig(rglwidget(width=1000, height=360, snapshot=TRUE), width=702, height=360*702/1000, caption="data (x1,x2 estimated density)")

A black image shows up where the image should be and beneath the image it shows this message:
Error : Chromote: timed out waiting for response to command Page.disable

What command can I use to increase the timeout period?
I tried options(chromote.timeout = 600) but it did not seem to increase the timeout.

**Comment by hadley** [comment]
Can you please provide a minimal reprex (*repr*oducible *ex*ample)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you! If you've never heard of a reprex before, start by reading [about the reprex package](https://reprex.tidyverse.org/index.html), including the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by Montereytony** [comment]
Sorry hadley, I may have figured out the issue or it went away, I just do not remember at this point, so let's close this issue.

**Comment by hadley** [comment]
@Montereytony no problems and thanks!

**Comment by PatrickRWright** [comment]
https://github.com/rstudio/chromote/issues/155
