### ISSUE TITLE
Can't close connections after starting session

### ISSUE THREAD

**Issue by hafen** [rstudio/chromote#23]
I'm really excited about this and the webshot2 package.

When using chromote inside functions in another R package, I need to be able to cleanly close connections or `R CMD CHECK` fails, complaining about unclosed connections.

If this package is still in a major state of flux, perhaps it is too premature to get into specifics, but I think this is a good thing to have in mind in general.

For example:

```r
b <- chromote::ChromoteSession$new()
showConnections()
```

```
  description
3 "/var/folders/wf/xv5yf5kj6pn458pcbx_vgsyr0000gn/T//RtmplFE5oJ/supervisor_s
tdinb90457c55c61" 
4 "/var/folders/wf/xv5yf5kj6pn458pcbx_vgsyr0000gn/T//RtmplFE5oJ/supervisor_s
tdoutb9045e34114b"
  class  mode text   isopen   can read can write
3 "fifo" "w+" "text" "opened" "yes"    "yes"    
4 "fifo" "w+" "text" "opened" "yes"    "yes"  
```

```r
b$parent$stop()                                                     
```

```
[2020-02-05 21:06:07] [error] handle_read_frame error: websocketpp.transport
:7 (End of File)
named list()
```

```r
b$parent$stop()                                                         
```

```
Error in self$send_command(msg, callback = callback_, error = error_,  : 
  Chromote object is closed.
```

```r
showConnections()
```

```
  description
3 "/var/folders/wf/xv5yf5kj6pn458pcbx_vgsyr0000gn/T//RtmplFE5oJ/supervisor_s
tdinb90457c55c61" 
4 "/var/folders/wf/xv5yf5kj6pn458pcbx_vgsyr0000gn/T//RtmplFE5oJ/supervisor_s
tdoutb9045e34114b"
  class  mode text   isopen   can read can write
3 "fifo" "w+" "text" "opened" "yes"    "yes"    
4 "fifo" "w+" "text" "opened" "yes"    "yes"  
```

Perhaps I'm just missing how to close things out. I looked in webshot2 to see what is done there, but didn't find anything.

For reference, I'm using chromote in [this package](https://github.com/hafen/r2d3svg).

**Comment by wch** [comment]
The supervisor connection is actually from the processx package -- it enables communication between the R process and a separate supervisor process. When `processx::process$new(.., supervise=T)` is called, it starts the supervisor if necessary, and tells it to watch the new child process. The supervisor process makes sure that, if the R process stops for whatever reason, it will kill the spawned process (in this case, Chrome).

The purpose of the connections is that it's how the R process communicates with the supervisor. The R process can tell the supervisor to watch additional processes. (I don't recall what the communication in the other direction is for, though.)

IIRC, once the processx supervisor is started, it keeps running until the R process ends, and there's no mechanism for stopping it.

I don't think I've ever seen this issue with `R CMD check`, though. You might want to check if the same error happens when you just run this in your package:

```R
processx::process$new("ls", supervise = TRUE)
```
