### ISSUE TITLE
Extract first element of CSS

### ISSUE THREAD

**Issue by markwsac** [rstudio/chromote#34]
Thanks for this great package. Can't fetch first element of CSS.

```
library(shiny)
runExample("01_hello", port = 1234)
```

Another Session
```
library(chromote)
b <- ChromoteSession$new()
b$view() # Opens a viewer to the headless browser, in a regular browser window
b$Page$navigate("http://localhost:1234")
b$screenshot("sidebar.png", selector = ".col-sm-4:nth-of-type(1)")
```

**Comment by wch** [comment]
For reference, this is the result:

![sidebar](https://user-images.githubusercontent.com/86978/110653677-181a2e80-8183-11eb-81d3-60d519ef6cc4.png)


The reason that it's capturing both the upper and lower divs is because Chromote uses `querySelectorAll()`, as opposed to `querySelector()`, which selects only the first item. This is by design.
https://github.com/rstudio/chromote/blob/ba9bffc2/R/screenshot.R#L287

If I run those two different queries in a normal browser's JS console, this is what happens:

![image](https://user-images.githubusercontent.com/86978/110654309-a393bf80-8183-11eb-8eda-01aed52f0677.png)

Here are the corresponding queries using Chromote:

```R
library(chromote)
b <- ChromoteSession$new()
b$view() # Opens a viewer to the headless browser, in a regular browser window
b$Page$navigate("http://localhost:1234")
# b$screenshot("sidebar.png", selector = ".col-sm-4:nth-of-type(1)", show = T)

doc <- b$DOM$getDocument()
root_node_id <- doc$root$nodeId

b$DOM$querySelector(root_node_id,".col-sm-4:nth-of-type(1)")
#> $nodeId
#> [1] 88
#> 
b$DOM$querySelectorAll(root_node_id,".col-sm-4:nth-of-type(1)")
#> $nodeIds
#> $nodeIds[[1]]
#> [1] 88
#> 
#> $nodeIds[[2]]
#> [1] 74
```

For now, you'll have to use a more different or more specific selector.
