### ISSUE TITLE
Does not work with Github Actions

### ISSUE THREAD

**Issue by markwsac** [rstudio/chromote#36]
Thanks for this great package. The code below works with local windows OS but returns blank when used in Github Actions. It does not throw any error. Does it require any dependency other than installing chromote? I tried with removing **b$view()** and using same version of R and chromote in both the environments

```
b <- ChromoteSession$new() 
b$view()
b$Page$navigate("https://www.cowin.gov.in/home/")
Sys.sleep(8)
b$Runtime$evaluate('document.querySelector("div.pin-search > input").focus()')

```

**Comment by wch** [comment]
I haven't tried it with GHA. Are you installing Chrome?

**Comment by cderv** [comment]
In GHA, Google Chrome should be installed, even on Windows runner https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#browsers-and-webdrivers

I have successfully used **webshot2** in GHA already which uses **chromote**. 

Chrome should not be an issue. FWIW, the other similar package **crrri** is tested using GHA for CI and it works fine. (mentioning as you have asked there also: https://github.com/RLesur/crrri/issues/106)

Is the url you want to reach an open url ?  It gives me error 403 in my browser and in R
```r
> curlGetHeaders("https://www.cowin.gov.in/home/")
[1] "HTTP/1.1 403 Forbidden\r\n"              "Server: awselb/2.0\r\n"                 
[3] "Date: Wed, 05 May 2021 10:11:40 GMT\r\n" "Content-Type: text/html\r\n"            
[5] "Content-Length: 118\r\n"                 "Connection: keep-alive\r\n"             
[7] "\r\n"                                   
attr(,"status")
[1] 403
```

It is then possible that Github Action can't access this url either by default. It may work on your computer because your local environment is already setup to get access to this website. Just some thoughts.

**Comment by markwsac** [comment]
Thanks for your detailed response. I also observed it returns 403 error in GHA. I tried setting custom headers and user-agent but no success. It works fine on my local.

**Comment by markwsac** [comment]
Just wanted to add - Google Chrome is already installed in GHA. `find_chrome()` returns path.

**Comment by dmurdoch** [comment]
This sounds like it might be a different issue, but when I rendered the `README.Rmd` file (https://github.com/dmurdoch/rgl/blob/master/README.Rmd) for `rgl` in GHA, the top image came out black.  That's a result of `webshot2` getting an image produced using WebGL.

**Comment by wch** [comment]
@dmurdoch I've read there are various flags you may be able to use to get headless chrome to render webGL, but I haven't tried it myself. `--disable-gpu` might work.

You can pass in the argument like this:

```R
m <- Chromote$new(browser = Chrome$new(args = "--disable-gpu"))

# Set this Chromote object as the default. Then any
# ChromoteSession$new() will be spawned from it.
set_default_chromote_object(m)
```

Also see:

https://stackoverflow.com/questions/39040370/how-do-i-enable-webgl-in-headless-chrome-in-ubuntu
https://stackoverflow.com/questions/62575117/force-headless-chromium-chrome-to-use-actual-gpu-instead-of-google-swiftshader

**Comment by cderv** [comment]
> I also observed it returns 403 error in GHA. I tried setting custom headers and user-agent but no success. It works fine on my local.

@markwsac it is not only on GHA. I can't access it on my side locally. I believe there could be special security on this website preventing access for other than the allowed users / IP / or else. You may need to reach out to the admin of this website to understand how this works. Then you'll be able to configure or maybe whitelist GHA for your need. I am not sure this is related directly to chromote or GHA.
